FROM python:3.12 as build

ADD run.py .
ADD emailhtml.py .
ADD credentials.py .
ADD newsletter.py .
ADD abstractivesummary.py .
ADD nonrandominput.py .
ADD input.py .
ADD sqs.py .
ADD sqsinput.py .

RUN pip3 install newsapi-python
RUN pip3 install torch
RUN pip3 install transformers

CMD ["python3", "./newsletter.py"]

